#!/bin/bash
#
# nginx - this script starts and stops the nginx daemin
#
# chkconfig:   - 85 15 
# description:  Nginx is an HTTP(S) server, HTTP(S) reverse 
#               proxy and IMAP/POP3 proxy server
# processname: nginx
# config:      /usr/local/nginx/conf/nginx.conf
# pidfile:     /usr/local/nginx/logs/nginx.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

nginx="NGINX_INPATH/sbin/nginx"
NGINX_CONF_FILE="NGINX_INPATH/conf/nginx.conf"
prog=$(basename $nginx)
lockfile=/var/lock/subsys/nginx


start() {
    [ -x $nginx ] || exit 5
    [ -f $NGINX_CONF_FILE ] || exit 6
    echo -n "Starting $prog: "
    $nginx -c $NGINX_CONF_FILE
    retval=$?
    if [ $retval -eq 0 ];then
        touch $lockfile
        echo 'Successfully'
    fi
    return $retval
}

stop() {
    echo -n "Stopping $prog: "
    $nginx -s stop
    retval=$?
    if [ $retval -eq 0 ];then
        rm -f $lockfile
        echo 'Successfully'
    fi
    return $retval
}

restart() {
    configtest || return $?
    stop
    start
}

reload() {
    configtest || return $?
    echo -n "Reloading $prog: "
    restart
    RETVAL=$?
    echo
}

configtest() {
  $nginx -t -c $NGINX_CONF_FILE
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q
        if [ $? -eq 0 ]; then
            rh_status
            exit
        fi
        $1
        ;;
    stop)
        rh_status_q
        if [ $? -eq 3 ]; then
            echo "$prog is stopped."
            exit
        fi
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q
        if [ $? -eq 3 ]; then
            echo "$prog is stopped."
            exit
        fi
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload|configtest}"
        exit 2
esac